# Site
name: "Dan Fitz"
title: "Dan Fitz"
description: "Blog posts about web development and life in general"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://blog.danfitz.com'
google_analytics: 'UA-145432763-1'
disqus: 'danfitz'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dan:
    name: Dan Fitz
    display_name: Dan Fitz
    gravatar: 3bf5217c9ca644feaab6ff3077f64f9d
    email: dan@danfitz.com
    web: https://blog.danfitz.com
    twitter: https://twitter.com/_danfitz
    description: "Front-end Developer. Bootcamp student at hackerYou. Graduating Oct 2019."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
